const learningToCode = {
    "title": "My coding journey",
    "slug": "my-coding-journey",
    "summary": "Computer science degree? Nope! Starting off with HTML and CSS? Nope! ...my unconventional route into the world of coding!",
    "categories": ["personal", "dev"],
    "text":
        "Growing up in Ireland, I didn't have even the slightest interest in programming. I vaguely recall some rather tedious computer science classes at school and messing around with geocities at one point ...but that was about it. To be honest, my impression of programming was that it was something very mathematical and dull! I sortof fell into a career in politics, and while that has certainly been interesting, it has always felt like there was something missing... ",
    "text1":
        "In my late 20s I happened to be living in Vancouver, Canada. I was attending a 'meetup' for currency market traders and became interested in a new 'mechanical' trading strategy - mechanical in the sense that currencies are bought or sold rigidly according to a set of rules. A friend I met at this meetup had built a simple script to run this strategy automatically - so rather than having to visually look at price charts for a buy/sell 'signal', this script would do that and place the orders accordingly. I thought this was SO cool and became very keen to learn everything I could about how the script worked. And so, one rainy winters night in a Waves coffee shop in Vancouver, my friend started explaining his code to me line by line: from for-loops to comments; from variables to functions...",
    "text2":
        "It was written in 'MetaQuotes Language 4' (MQL4) a specialised language kinda similar to C. At first I was only interested in the finished product - being able to build a program that would trade the markets automatically for me. But the more I learned and played about with the code, the more I became fascinated by the process of coding generally - it was all so logical yet creative; elegant yet powerful...I was hooked! Based on this single script (and a bit of google-fu) I started building my own trading scripts. At first I barely understood what I was doing. I didn't understand the constituent parts of a 'for loop' for example, I only knew what that block of code *did* and so I reused it accordingly. But I learnt fast by making changes and improvements to the code, and before long I was making my own trading bots from scratch (I definitely agree with the advice that the best way to learn to code is by playing about and making things!).",
    "text3":
        "Still, I never considered taking this new-found skill any further than the very specific language I was using and for the very specific purpose I was using it for. Two things changed this. Firstly, I discovered the amazing world of open source education and its associated communities, which made learning so accessible and empowered me to take my new found interest further than I would have thought possible. Secondly, due to a curveball life threw me, I moved to San Jose California - the heart of Silicon Valley - of all places. With some time off between jobs, and in the literal shadow of Facebook, Google and other famous HQs, I had a lot of time to put into learning. I began with FreeCodeCamp's Responsive Web Design track and Harvard's famous CS50 Computer Science Program - I really can't recommend either of these courses enough (I'll do a separate blog on courses, youtube channels and other resources I found helpful). I gravitated towards web development, partially because that is what most people seemed to recommend, but also because it seemed to open the most doors and I still wasn't sure what field of development I wanted to get into (eg game development, app development etc). After building my first basic HTML/CSS website (a tribute page to Tim Berners-Lee!), I started learning Javascript and just fell in love with it - possibly because of it's similarity to C, which made it relatively easy for me to pick up!",
    "text4":
        "Another advantage of being in San Jose was the networking. There were meetups and FreeCodeCamp study groups galore! I not only met people like me that were learning to code from scratch, but more importantly I also met professional developers who were either self-taught or transitioned into the industry from something completely irrelevant. This was a huge source of inspiration for me, and it was so helpful chatting to these developers - both in person, and connecting via social media. I applied to join a Web Developer Bootcamp in Vancouver BC, but life through another few curveballs - visa issues, and COVID19. Moving back to an Ireland in lockdown, my self-learning continued in lockdown and on either side of a busy 9-5 career. I had a lot of fun learning React, Redux and React-Native (and assosciated technologies) and by late 2020 was building complex, full-stack web applications and mobile apps, with user authentication, database integration and advanced UIs. Having started off quite broad - learning Python, C, general Computer Science etc - I began to 'find my niche' as a React/Javascript developer. At the time of writing I'm starting to apply for junior jobs in this field and while I'm excited for this next step, I'm all about enjoying the journey :).",

    "blockquote": "the amazing world of open source education and its associated communities made learning so accessible and empowered me to take my new found interest further than I would have thought possible.",
    "picture": require("../BlogPics/wave_coffee.jpg"),
    "caption": "The coffee shop in Vancouver, Canada where I was taught the basics!",
    "picture2": require("../BlogPics/MQL4.JPG"),
    "caption2": "Some of my first code written in MQL4 (C)",
    "picture3": require("../BlogPics/FacebookHQ.jpg"),
    "caption3": "At Facebook HQ in California, 2019.",
    "date": "1st April, 2021",

}

export default learningToCode